name -> id for clientoptions in readme (#524)
## Summary
I pulled latest and tried the example code in the readme's getting
started:

```
const inngest = new Inngest({ name: "My App" });
```
and got:

```
src/index.ts:147:31 - error TS2345: Argument of type '{ name: string; }' is not assignable to parameter of type 'ClientOptions'.
  Object literal may only specify known properties, and 'name' does not exist in type 'ClientOptions'.

147 const inngest = new Inngest({ name: "My App" });
```

Guessing the readme has drifted from the code and it should be `id` and
not `name`.

## Checklist
<!-- Tick these items off as you progress. -->
<!-- If an item isn't applicable, ideally please strikeout the item by
wrapping it in "~~"" and suffix it with "N/A My reason for skipping
this." -->
<!-- e.g. "- [ ] ~~Added tests~~ N/A Only touches docs" -->

- [ ] Added a [docs PR](https://github.com/inngest/website) that
references this PR
- [ ] Added unit/integration tests
- [ ] Added changesets if applicable

## Related
<!-- A space for any related links, issues, or PRs. -->
<!-- Linear issues are autolinked. -->
<!-- e.g. - INN-123 -->
<!-- GitHub issues/PRs can be linked using shorthand. -->
<!-- e.g. "- inngest/inngest#123" -->
<!-- Feel free to remove this section if there are no applicable related
links.-->
- INN-

Co-authored-by: Jacob Heric <jacob@jacobheric.com:q!>