Fix throw when cancelling a locked stream (#965)
## Summary
<!-- Succinctly describe your change, providing context, what you've
changed, and why. -->

Fix `@inngest/realtime` throwing:

```
TypeError: Failed to execute 'cancel' on 'ReadableStream': Cannot cancel a locked stream
```

This is caused by the reader (in an async `for await` loop) still being
active, and us having to explicit way of cleaning it up.

## Checklist
<!-- Tick these items off as you progress. -->
<!-- If an item isn't applicable, ideally please strikeout the item by
wrapping it in "~~"" and suffix it with "N/A My reason for skipping
this." -->
<!-- e.g. "- [ ] ~~Added tests~~ N/A Only touches docs" -->

- [ ] ~Added a [docs PR](https://github.com/inngest/website) that
references this PR~ N/A Bug fix
- [ ] Added unit/integration tests
- [x] Added changesets if applicable

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>